name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Ставим Java 11 — она идеальна: её понимает и Gradle, и Cordova 10+
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # NodeJS 16 отлично подходит
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cordova
      run: npm install -g cordova@10.0.0

    # Ставим чистую cordova-android 10-й версии. Без костылей.
    - name: Build Cordova Project
      run: |
        cordova platform add android@10.1.2
        cordova build android --debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk